--- 
title: "Manitou Experimental Forest UAS Mission Data Summary"
author: "George Woolsey"
date: "`r format(Sys.time(), '%d %B, %Y')`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    includes:
      in_header: header.html
documentclass: book
book_filename: "manitou_uas_202406"
output_dir: "../docs"
language:
  ui:
    chapter_name: "Section "
delete_merged_file: true
bibliography: [packages.bib]
biblio-style: apalike
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/research-institute-for-nature-and-forest.csl
suppress-bibliography: false
lang: en-US
zotero: true
link-citations: true
description: "Using the bookdown package to write a book of data exploration. The output format for this example is bookdown::gitbook."
---

# Introduction

This project summarizes processed point cloud data created using structure from motion (SfM) photogrammetry methods on imagery collected from Unmanned Aircraft System (UAS) flights completed in June 2024. UAS imagery was collected using a DJI Phantom 4 Pro equipped with a 20 megapixel metal oxide semiconductor red-green-blue camera at a fixed 8.8 mm focal length. Flights followed a pre-programmed serpentine flight paths at an altitude of 120 m above ground level, using a nadir camera orientation, with 80% forward and side image overlap.The UAV imagery was processed in Agisoft Metashape using the routine outlined by [Tinkham and Swayze (2021)](https://scholar.google.com/scholar?cluster=11260597505702247290&hl=en&as_sdt=0,6) to produce an SfM point cloud for optimized tree detection. 

The SfM-derived point cloud was processed using the methods outlined by [Swayze and Tinkham (2022)](https://scholar.google.com/scholar?oi=bibs&hl=en&cluster=10655866445299954513). Specifically, [this script](https://github.com/georgewoolsey/point_cloud_tree_detection_ex/blob/da5c8a13e9b2f2914b306201605e907643b3006d/src/point_cloud_processing.R) which is outlined in detail at it's [parent Github repository](https://georgewoolsey.github.io/point_cloud_tree_detection_ex/) was used to process the raw point cloud data.

SfM techniques using UAS data reliably identify most tree locations and heights in open-canopied forests. However, their ability to characterize diameter at breast height (DBH) is limited to estimates of a fraction of trees within the area. SfM-derived DBH was estimated at the tree level following the methods outlined by [Tinkham et al. (2022)](https://scholar.google.com/scholar?cluster=14807895789640069059&hl=en&as_sdt=0,6).


```{r include=FALSE, echo=FALSE, eval=T}
knitr::write_bib(c(
  .packages(),
  "bookdown"
  , "knitr"
  , "rmarkdown"
  , "tidyverse"
  , "viridis"
  , "scales"
  , "latex2exp"
  , "terra"
  , "sf"
  , "stars"
  , "kableExtra"
  , "patchwork"
  , "mapview"
  , "leafpop"
  , "ggnewscale"
  , "ggtext"
  , "ggpubr"
  , "pdftools"
  , "brms"
  , "Metrics"
), 'packages.bib')
```
